"use client";
import { signIn } from "next-auth/react";
import { ArrowUpRight, ShieldCheck, BookOpen, Check, Phone, MessageCircle, Sparkles } from "lucide-react";
import { useState } from "react";

const topics = ["Read balance sheets and cash flow with confidence", "Understand financial ratios and business quality", "Explore growth opportunities and long-term potential", "Build a framework for valuation and risk", "Learn moving averages, RSI, MACD and chart essentials", "Revisit lessons with class recordings"];
const whatsapp = "https://wa.me/919025839615?text=Hello%2C%20I%20would%20like%20details%20about%20the%20Senganthal%20fundamental%20analysis%20classes.";

export default function Login({ configured, error, previewAvailable }: {configured: boolean; error?: string; previewAvailable: boolean}) {
  const [busy, setBusy] = useState(false);
  const [signInError, setSignInError] = useState("");
  return <main className="anniversary-login">
    <header className="anniversary-header"><a href="/login" className="anniversary-brand"><img src="/senganthal-logo.jpg" alt="Senganthal"/><span><strong lang="ta">செங்காந்தள்</strong><small>RESEARCH & COMMUNITY</small></span></a><a href="/about">Our story <ArrowUpRight size={15}/></a></header>
    <div className="anniversary-grid">
      <section className="anniversary-story">
        <div className="anniversary-kicker"><span/> ONE YEAR. A SHARED JOURNEY.</div>
        <div className="anniversary-hero"><div className="anniversary-medallion" aria-label="Celebrating our first anniversary"><div className="anniversary-orbit" aria-hidden="true"/><Sparkles className="anniversary-spark spark-one" aria-hidden="true"/><Sparkles className="anniversary-spark spark-two" aria-hidden="true"/><span className="anniversary-one">1<sup>st</sup></span><span className="anniversary-label">ANNIVERSARY</span><span className="anniversary-year">GROWING TOGETHER</span></div><div className="anniversary-heading"><h1>A year of learning.<br/><em>A future of possibilities.</em></h1><p>Celebrating our first year of asking better questions, understanding businesses, and growing as a community.</p><p className="anniversary-tamil" lang="ta">சேர்ந்து கற்போம். சேர்ந்து வளர்வோம்.</p></div></div>
        <section className="anniversary-course"><div className="anniversary-course-heading"><span className="anniversary-book"><BookOpen size={21}/></span><div><span className="anniversary-overline">LEARN WITH SENGANTHAL</span><h2>Make fundamentals your foundation.</h2></div></div><p>A practical learning journey to help you research companies with more clarity and confidence.</p><ul>{topics.map(topic=><li key={topic}><Check size={16}/><span>{topic}</span></li>)}</ul><a className="anniversary-course-link" href={whatsapp} target="_blank" rel="noopener noreferrer">Ask about classes & fees <ArrowUpRight size={17}/></a></section>
      </section>
      <aside className="anniversary-access"><section className="anniversary-card"><span className="anniversary-member"><ShieldCheck size={15}/> YOUR RESEARCH WORKSPACE</span><h2>Welcome to<br/>your next chapter.</h2><p>Connect with your community and continue your stock research.</p>{(error || signInError) && <div role="alert" className="alert error">{signInError || (error === "ServiceUnavailable" ? "The team database could not be reached. Please try again shortly or contact your administrator." : error === "AccessDenied" ? "This account is unavailable or its access has been revoked. Please contact your administrator." : "Sign-in could not be completed. Check your connection or contact your administrator.")}</div>}{!configured && <div className="alert">Google sign-in is awaiting setup. Your administrator needs to connect Google and the team database before members can sign in.</div>}<button className="google-button" disabled={!configured || busy} onClick={async () => {setBusy(true);setSignInError("");try{await signIn("google", { callbackUrl: "/" });}catch{setSignInError("Could not open Google sign-in. Check your connection and try again.");setBusy(false);}}}><span className="google-g">G</span>{busy ? "Opening Google…" : "Continue with Google"}<ArrowUpRight size={18}/></button><p className="anniversary-privacy"><ShieldCheck size={15}/> Your Google password stays private.<br/>Workspace access is managed by your team.</p>{previewAvailable && <a href="/preview" className="anniversary-preview">Take a look inside <ArrowUpRight size={16}/></a>}<div className="anniversary-card-footer"><Sparkles size={16}/> A little wiser. A little closer. One year together.</div></section>
        <section className="anniversary-contact"><span className="anniversary-overline">LET’S LEARN TOGETHER</span><h2>Your learning journey starts here.</h2><p>Get class details, fee information, and help joining our learning community.</p><a className="anniversary-phone" href="tel:+919025839615">+91 90258 39615</a><div className="anniversary-contact-actions"><a href="tel:+919025839615"><Phone size={16}/> Call us</a><a href={whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> WhatsApp us</a></div><details><summary>Already paid for classes?</summary><p>Send your name and transaction ID to the number above so the team can arrange your class and WhatsApp group access. Class fees cover learning sessions, not this app or its market data.</p></details></section>
      </aside>
    </div><footer className="anniversary-footer"><span>SENGANTHAL <span aria-hidden="true">✦</span> Celebrating one year of community</span><span>Educational research only. Not investment advice.</span></footer>
  </main>;
}
